### ISSUE TITLE
ERROR VIA NODE.JS CMD PROMPT

### ISSUE THREAD

**Issue by Teslaguy** [TahaGorme/discord-wizard#5]
Microsoft Windows [Version 10.0.19045.4651]
(c) Microsoft Corporation. All rights reserved.

C:\Users\danth>cd discord-wizard
The system cannot find the path specified.

C:\Users\danth>cd Downloads

C:\Users\danth\Downloads>cd discord-wizard
The system cannot find the path specified.

C:\Users\danth\Downloads>cd C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main

C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main>npm i

added 147 packages, and audited 148 packages in 2m

15 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice
npm notice New major version of npm available! 9.5.1 -> 10.8.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
npm notice Run npm install -g npm@10.8.2 to update!
npm notice

C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main>npm audit fix

added 40 packages, removed 14 packages, changed 18 packages, and audited 174 packages in 2m

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main>node .
Fetched 1000 emails.
 Email: o.ct.avi.a.bl.odrein4@gmail.com Password: 5@jDyGGJyrBR9H#j
C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:50
            this.#timeoutError = new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: Waiting for selector `#app-mount > div > div > div.grid-3d2PVT.heroBackground-itJzsn > div.row-31oovZ.heroContainer-3YphMz > div > div.ctaContainer-5100Xg > button` failed: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:50:34)
    at IsolatedWorld.waitForFunction (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Realm.js:25:26)
    at CSSQueryHandler.waitFor (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\QueryHandler.js:172:95)
    at async CdpFrame.waitForSelector (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:522:21)
    at async CdpPage.waitForSelector (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:1305:20)
    at async C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\index.js:204:7

Node.js v18.16.0

C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main>node install puppeteer-core
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\install'
←[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:920:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:23:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

Node.js v18.16.0

C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main>node .
Fetched 1000 emails.
 Email: kentkouh+bubtz@gmail.com Password: $QjFW6p715KJJ!9N
C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:50
            this.#timeoutError = new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: Waiting for selector `#app-mount > div > div > div.grid-3d2PVT.heroBackground-itJzsn > div.row-31oovZ.heroContainer-3YphMz > div > div.ctaContainer-5100Xg > button` failed: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:50:34)
    at IsolatedWorld.waitForFunction (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Realm.js:25:26)
    at CSSQueryHandler.waitFor (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\QueryHandler.js:172:95)
    at async CdpFrame.waitForSelector (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:522:21)
    at async CdpPage.waitForSelector (C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:1305:20)
    at async C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main\index.js:204:7

Node.js v18.16.0

C:\Users\danth\Downloads\discord-wizard-main\discord-wizard-main>

**Comment by Teslaguy** [comment]
i will try converting this into python.

**Comment by TahaGorme** [comment]
hello, thank you for showing interest. this is very old and things have changed now.
emailnator emails are banned from discord, and changing your email to an emailnator email will terminate your account. contact me on discord if you would like to get in touch. @uutu on discord

**Comment by Teslaguy** [comment]
> hello, thank you for showing interest. this is very old and things have changed now. emailnator emails are banned from discord, and changing your email to an emailnator email willterminate your account. contact me on discord if you would like to get in touch. @uutu on discord

Sounds good, Do you know if you will be making any other projects similar to this?
